print("{}".format("*"*50))
print("{}".format("2020년 2학기 파이썬프로그래밍 기말고사 답안지"))
print("{}".format("*"*50))
print()
print("{}".format("*"*40))
print("{}\t\t:\t{}".format("이름","박병현"))
print("{}\t:\t{}".format("학번(ID)","2016112568"))
print("{}\t\t:\t{}".format("학과","산업시스템공학과"))
print("{}".format("*"*40))
